### ISSUE TITLE
Add season plugin option

### ISSUE THREAD

**Issue by raae** [queen-raae/gatsby-plugin-let-it-snow#2]
At the moment it's always on.

It should be able to set and forget, having it stop/start for each holiday season...

**Comment by raae** [comment]
Maybe name the option "season":
```
season: {
   start: <date>
   end: <date>
}
```

**Comment by raae** [comment]
We could add default - November 15th to December 31st ?

**Comment by raae** [comment]
WP calls it snow_season and it was December 1st and January 4th.

**Comment by PaulieScanlon** [comment]
@raae  I've created a PR for a first attempt for how we could do the `season` option [pull/11](https://github.com/queen-raae/gatsby-plugin-let-it-snow/pull/11)
