### ISSUE TITLE
Support css variables in the color option

### ISSUE THREAD

**Issue by bradgarropy** [queen-raae/gatsby-plugin-let-it-snow#30]
In order to support light / dark mode, or different themes, it would be very helpful if the `colors` option supported CSS custom properties like this:

```
colors: ["var(--primary)", "var(--secondary)"]
```

Great work so far, thanks!

**Comment by bradgarropy** [comment]
I have a feeling accomplishing this might require changes to the underlying [`canvas-confetti`](https://github.com/catdad/canvas-confetti) library somewhere around [these lines](https://github.com/catdad/canvas-confetti/blob/master/src/confetti.js#L224-L240).

**Comment by raae** [comment]
I am also thinking I can pull the variable with css before giving them to `canvas-confetti`, but would be a cool addition to  `canvas-confetti` though.

**Comment by raae** [comment]
Take a look at #31, do you think that would solve your use case?

**Comment by bradgarropy** [comment]
I was reading it as you were writing it apparently 😆 

Although the implementation is limited to the `:root`, that would totally work for my use case today.
