### ISSUE TITLE
Let it emoji snow

### ISSUE THREAD

**Issue by PaulieScanlon** [queen-raae/gatsby-plugin-let-it-snow#9]
I'd like to create another plugin option to pass either strings/emojis or if it works in a similar way maybe even React components.

**Comment by raae** [comment]
Why not!

**Comment by PaulieScanlon** [comment]
Unfortnulately we won't be able to do this. `canvas-confetti` only supports x2 types of shapes:

```javascript
// index.d.ts
 type shape = 'square' | 'circle';
```
